[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "mqttclient_python"
author = "Sci-Bots"
author-email = "info@sci-bots.com"
home-page = "sci-bots.com"
license= "BSD-2-Clause"
